version: "3.9"
services:

  ui:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: ManagerX-UI
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    networks:
      - network

networks:
  network:
