version: "3.9"
services:

  ui:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    container_name: ManagerX-UI
    restart: always
    ports:
      - "3000:80"
    env_file: .env